### ISSUE TITLE
L1 - L4 keys

### ISSUE THREAD

**Issue by mf0hka** [tuxmark5/ApexCtl#21]
Is there a way to remap the L1 - L4  (lighting keys)
to specpific colour modes?

**Comment by tuxmark5** [comment]
You can create 4 scripts invoke ApexCtl that apply a desired color scheme. Then you can add these scripts to sudoers so you may call them with sudo without having to enter the root password. After that you can bind these scripts to L1-L4 keys using some utility like xbindkeys.
