### ISSUE TITLE
Archlinux build failed

### ISSUE THREAD

**Issue by BanditSan** [tuxmark5/ApexCtl#25]
make fails whit error. All required dependencies are installed.

~/aur/ApexCtl$ make
cabal configure
Resolving dependencies...
Configuring ApexCtl-0.0.2...
cabal build
Building ApexCtl-0.0.2...
Preprocessing executable 'apexctl' for ApexCtl-0.0.2...
[1 of 1] Compiling Main             ( src/Main.hs, dist/build/apexctl/apexctl-tmp/Main.o )

src/Main.hs:225:3:
    Couldn't match expected type ‘a0
                                  -> a1 -> ByteString -> Timeout -> IO ()’
                with actual type ‘IO ()’
    The function ‘writeControlExact’ is applied to 8 arguments,
    but its type ‘DeviceHandle -> ControlSetup -> WriteExactAction’
    has only four
    In a stmt of a 'do' block:
      writeControlExact
        devHndl Class ToInterface _SET_REPORT 512 0 d noTimeout
    In the expression:
      do { putStrLn "WRITING SET_REPORT";
           writeControlExact
             devHndl Class ToInterface _SET_REPORT 512 0 d noTimeout }

src/Main.hs:226:5:
    Couldn't match expected type ‘ControlSetup’
                with actual type ‘RequestType’
    In the second argument of ‘writeControlExact’, namely ‘Class’
    In a stmt of a 'do' block:
      writeControlExact
        devHndl Class ToInterface _SET_REPORT 512 0 d noTimeout

src/Main.hs:227:5:
    Couldn't match expected type ‘ByteString’
                with actual type ‘Recipient’
    In the third argument of ‘writeControlExact’, namely ‘ToInterface’
    In a stmt of a 'do' block:
      writeControlExact
        devHndl Class ToInterface _SET_REPORT 512 0 d noTimeout

src/Main.hs:228:5:
    Couldn't match type ‘Word8’ with ‘Int’
    Expected type: Timeout
      Actual type: Request
    In the fourth argument of ‘writeControlExact’, namely ‘_SET_REPORT’
    In a stmt of a 'do' block:
      writeControlExact
        devHndl Class ToInterface _SET_REPORT 512 0 d noTimeout

src/Main.hs:241:13:
    Couldn't match expected type ‘a2
                                  -> a3 -> a4 -> Timeout -> IO (ByteString, a5)’
                with actual type ‘IO (ByteString, Status)’
    The function ‘readControl’ is applied to 8 arguments,
    but its type ‘DeviceHandle -> ControlSetup -> ReadAction’
    has only four
    In a stmt of a 'do' block:
      (r, s) <- readControl
                  devHndl Class ToInterface _SET_REPORT 512 0 32 noTimeout
    In the expression:
      do { (r, s) <- readControl
                       devHndl Class ToInterface _SET_REPORT 512 0 32 noTimeout;
           putStrLn $ hex r;
           putStrLn $ show s }

src/Main.hs:242:5:
    Couldn't match expected type ‘ControlSetup’
                with actual type ‘RequestType’
    In the second argument of ‘readControl’, namely ‘Class’
    In a stmt of a 'do' block:
      (r, s) <- readControl
                  devHndl Class ToInterface _SET_REPORT 512 0 32 noTimeout

src/Main.hs:243:5:
    Couldn't match type ‘Recipient’ with ‘Int’
    Expected type: Size
      Actual type: Recipient
    In the third argument of ‘readControl’, namely ‘ToInterface’
    In a stmt of a 'do' block:
      (r, s) <- readControl
                  devHndl Class ToInterface _SET_REPORT 512 0 32 noTimeout

src/Main.hs:244:5:
    Couldn't match type ‘Word8’ with ‘Int’
    Expected type: Timeout
      Actual type: Request
    In the fourth argument of ‘readControl’, namely ‘_SET_REPORT’
    In a stmt of a 'do' block:
      (r, s) <- readControl
                  devHndl Class ToInterface _SET_REPORT 512 0 32 noTimeout
makefile:21: recipe for target 'dist/build/apexctl/apexctl' failed
make: *** [dist/build/apexctl/apexctl] Error 1

~/aur/ApexCtl$ pacman -Ss | egrep 'ghc|libusb|cabal|pkg-config'
core/libusb 1.0.19-1 [installed]
core/pkg-config 0.28-2 (base-devel) [installed]
extra/cabal-install 1.22.0.0-1 [installed]
extra/ghc 7.8.4-1 [installed]

**Comment by tuxmark5** [comment]
At a glance it looks like the newest Haskell USB library has some API changes that are incompatible with previous versions.

**Comment by BanditSan** [comment]
Which version i should use to make it work?

**Comment by tuxmark5** [comment]
I'm updating my haskell installation right now. After that I'll update ApexCtl so it would work with the latest version of the USB library.

**Comment by tuxmark5** [comment]
So here is the situation. Ubuntu 14.04 by default ships ghc 7.6.3. The newest Haskell usb library is version 1.3.0.0, which requires at least 7.8 to compile. So to use usb-1.3.0.0 I would need to force users to upgrade ghc to 7.8, which isn't a fun thing to do. So for now I will not patch/update ApexCtl to support usb-1.3.0.0. So you'll have to downgrade your usb library to 1.2.0.1.

**Comment by tuxmark5** [comment]
I've just pushed a .cabal file patch which specifies usb library dependency version and thus resolves this issue.

**Comment by BanditSan** [comment]
Bad Ubuntu is reference. Arch mirror does not have any more such old version of ghc.

$ downgrade ghc
Available packages:

   1) ghc-7.8.4-1-x86_64.pkg.tar.xz (local)
   2) ghc-7.8.3-2-x86_64.pkg.tar.xz (remote)
   3) ghc-7.8.2-4-x86_64.pkg.tar.xz (remote)
   4) ghc-7.8.2-3-x86_64.pkg.tar.xz (remote)

**Comment by tuxmark5** [comment]
You can use newer ghc versions too. Just git clone the latest ApexCtl version and install it normally. Everything should work fine.

And as for Ubuntu as reference: I'm using it, because I'm too lazy to frequently update stuff :)

**Comment by BanditSan** [comment]
Just cloned latest ApexCtl.

cabal configure
Resolving dependencies...
Configuring ApexCtl-0.0.2...
cabal: At least the following dependencies are missing:
usb ==1.2.0.1
makefile:21: recipe for target 'dist/build/apexctl/apexctl' failed
make: *** [dist/build/apexctl/apexctl] Error 1

Whit latest ghc version usb-1.2.0.1 fails to install :)

Downloading usb-1.2.0.1...
Configuring usb-1.2.0.1...
Building usb-1.2.0.1...
Failed to install usb-1.2.0.1
Build log ( /home/marius/.cabal/logs/usb-1.2.0.1.log ):
[1 of 1] Compiling Main             ( /tmp/usb-1.2.0.1-21939/usb-1.2.0.1/dist/setup/setup.hs, /tmp/usb-1.2.0.1-21939/usb-1.2.0.1/dist/setup/Main.o )
Linking /tmp/usb-1.2.0.1-21939/usb-1.2.0.1/dist/setup/setup ...
Configuring usb-1.2.0.1...
Building usb-1.2.0.1...
Preprocessing library usb-1.2.0.1...

System/USB/Base.hs:78:18:
    Could not find module ‘Data.Vector’
    There are files missing in the ‘vector-0.10.12.2’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.

System/USB/Base.hs:126:18:
    Could not find module ‘Data.Vector.Unboxed’
    There are files missing in the ‘vector-0.10.12.2’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.

System/USB/Base.hs:127:18:
    Could not find module ‘Data.Vector.Storable’
    There are files missing in the ‘vector-0.10.12.2’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.

System/USB/Base.hs:128:18:
    Could not find module ‘Data.Vector.Generic’
    There are files missing in the ‘vector-0.10.12.2’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.

System/USB/Base.hs:129:18:
    Could not find module ‘Data.Vector.Generic.Mutable’
    There are files missing in the ‘vector-0.10.12.2’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.

System/USB/IO/StandardDeviceRequests.hs:64:8:
    Could not find module ‘Bindings.Libusb’
    There are files missing in the ‘bindings-libusb-1.4.5.0’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.

Timeval.hs:24:8:
    Could not find module ‘Bindings.Libusb.PollingAndTiming’
    There are files missing in the ‘bindings-libusb-1.4.5.0’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
usb-1.2.0.1 failed during the building phase. The exception was:
ExitFailure 1

**Comment by tuxmark5** [comment]
Looks like your ghc packages are broken.
If you don't use any other haskell libraries or binaries, you can remove (or just rename) ~/.ghc and ~/.cabal directories and try installing ApexCtl again.

**Comment by BanditSan** [comment]
OK that was problem. Now compiled and works :)

Off-topic question:
Why you using such exotic language for this project? :)

**Comment by tuxmark5** [comment]
I've used Haskell for my previous keyboard utility (which would enable extra macro keys for some Razer keyboards), so this was a fairly easy decision, because I could just copy paste some of the code.

And why I used Haskell for the previous project - not sure. At the time when I wrote the first utility I guess I was really fascinated with Haskell. Plus it had USB bindings that had quite a nice interface (as opposed to using native C library).

**Comment by BanditSan** [comment]
Got your point :) Now only small thing left. M9-M12 and L1-L4 whit same keycode mapped.

**Comment by tuxmark5** [comment]
You need to place the provided 90-apex.hwdb to /etc/udev/hwdb.d. This will provide low level scancode to keycode mappings. Then you'll need to modify or replace your ~/.Xmodmap to map these new keycodes to something that X can understand. Both files can be found in config directory.

Alternatively you can use "make install", which should do those things for you, but I can't guarantee it, because I wasn't the one who wrote that Makefile.

**Comment by kiwistrongis** [comment]
You could do `make local-install` as well, which'll make the ~/.Xmodmap file for you. ( you've got to do `sudo make install` to get the udev rules. )
