### ISSUE TITLE
mx keys have the same functionality as media keys (ubuntu)

### ISSUE THREAD

**Issue by Qwertie-** [tuxmark5/ApexCtl#29]
The mx keys on the left have the same functionality as the media keys on the right which means I cant remap them because the os sees them as the media keys which are already mapped.

**Comment by tuxmark5** [comment]
Have you installed hwdb file which assigns unique IDs to each of the keys?

**Comment by Zimmux** [comment]
We should really mention the hwdb file in the installation guide,

**Comment by Qwertie-** [comment]
@tuxmark5 I have not. Could you tell me how?

**Comment by tuxmark5** [comment]
Copy "config/90-apex.hwdb" to "/etc/udev/hwdb.d/90-apex.hwdb" and reboot your computer.

**Comment by Qwertie-** [comment]
That has mostly fixed it but now mx9 is "(" and mx10 is ")"

**Comment by tuxmark5** [comment]
Also copy "config/Xmodmap" to ~/.Xmodmap and make sure that it is loaded when your session starts.

**Comment by Qwertie-** [comment]
I copied the file but how do I get it to load when the session starts?

**Comment by tuxmark5** [comment]
The file can be loaded manually using "xmodmap ~/.Xmodmap", but most DEs should do this automatically.

**Comment by Qwertie-** [comment]
Ah that did it. Thanks a lot for making this tool so I can finally make the most of my keyboard :D

**Comment by tuxmark5** [comment]
@Zimmux Yes. We really need some FAQ or hwdm/Xmodmap entry in the README.

@Qwertie- You're welcome :)

**Comment by delaman** [comment]
I am having a similar issue however on Xubuntu.  I have installed the system wide depends, however I am not able to install the cabal depends.

```
xubuntu@xubuntu:~/git/ApexCtl$ make
cabal configure
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
Configuring ApexCtl-0.0.2...
cabal: At least the following dependencies are missing:
cmdargs -any, usb ==1.2.0.1, vector -any
makefile:21: recipe for target 'dist/build/apexctl/apexctl' failed
make: *** [dist/build/apexctl/apexctl] Error 1
xubuntu@xubuntu:~/git/ApexCtl$ cabal update
Downloading the latest package list from hackage.haskell.org
Skipping download: Local and remote files match.
xubuntu@xubuntu:~/git/ApexCtl$ cabal install usb-1.2.0.1 cmdargs
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
cabal: There is no package named 'usb'.
There is no package named 'cmdargs'.
You may need to run 'cabal update' to get the latest list of available
packages.
xubuntu@xubuntu:~/git/ApexCtl$ 
```

Any ideas? 

Thanks

**Comment by kiwistrongis** [comment]
Looks like you missed the `cabal update` step. Try the following:

```bash
cabal update
cabal install usb-1.2.0.1 cmdargs
make
```
