### ISSUE TITLE
MX keys same function as media keys?

### ISSUE THREAD

**Issue by mrgrey1** [tuxmark5/ApexCtl#31]
Running KDE Debian and having the same problem as [issue 29.](https://github.com/tuxmark5/ApexCtl/issues/29) My MX keys have the same functions as the media keys, the M5 key will put my system to sleep. I have checked the solutions on issue 29, the files 90-apex.hwdb and .Xmodmap are in their correct locations. I have tried running "sudo udevadm hwdb --update" manually and get "missing or unknown command". "sudo udevadm control --reload" returns without issue. Any help appreciated.

Edit: Figured out my problem. Debian stable (wheezy) is on udev v175 which is too old for ApexCtl to function. I updated my system to testing (jessie) which has udev v215 and ApexCtl is now working as intended.  To the devs, thanks for this program, I bought this keyboard specifically because I saw the macros were supported in Debian and my g15 was dying. May I recomend you specify somewhere in the Readme what version udev is required and add a note to the Debian install instructions that Wheezy will not work without updated udev. Would have saved me some time. ;)
Cheers.

**Comment by tuxmark5** [comment]
Sorry for not replying in time. I've noticed the email notification on my phone, but forgot to follow it up when I got to my PC. 

And yes, minimum required version of udev is v206. There was similar problem in issue #4. But I completely agree with you, this should be mentioned somewhere.

**Comment by kiwistrongis** [comment]
Just added it to the readme: 412d4c543f69304868cd3de2ab4b1314727f1881.
