### ISSUE TITLE
Apex Logo Key

### ISSUE THREAD

**Issue by mrgrey1** [tuxmark5/ApexCtl#32]
The Apex Logo key or right hand side Super key appears to have been overlooked.

**Comment by tuxmark5** [comment]
I'm fairly certain that this key is firmware controlled and the keyboard does not send events when you press it. So this bug/issue might be unsolvable.

**Comment by mrgrey1** [comment]
Ah bummer. Thanks for the info. I think I can manage with just one key not working ;)
Thanks for everything.
