### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by wvanbreukelen** [tuxmark5/ApexCtl#35]
Hi there,

I successfully managed to build ApexCtl for Windows with ghc, libusb, and cmdargs. 
Now, when I run apexctl.exe I get the following error:

```
libusb: warning [init_device] could not get node connection information for device '\\.\USB#VID_24AE&PID_2002&MI_01#7&1003B8A6&0&0001': [87]
```

Does someone of you have a clue how to fix this issue? Thanks!

**Comment by tuxmark5** [comment]
I've no idea that ApexCtl could even compile on Windows. I don't see much reason to use ApexCtl on Windows since Steelseries provides native tools that are more feature complete.
