### ISSUE TITLE
New SSE3 options

### ISSUE THREAD

**Issue by Quintin96** [tuxmark5/ApexCtl#36]
First of all, thanks a ton for this.

I just wanted to know if we will be seeing an update to this introducing the updates that SteelSeries brought in their SSE3 with the ColourShift and Gamesense. I play Dota 2 mostly and would absolutely love to have the settings that SSE3 provides with the Gamesense for Dota 2.

I am currently a student and have done C++ and will be completing C# pretty soon. Needless to say I haven't been able to do much programming outside of pretty basic college projects, but I would be glad to help however I can if you would like to implement this.

**Comment by tuxmark5** [comment]
No, currently there are no plans to support features like that as it's outside of ApexCtl's scope.

Ideally, there should be an open-source project that would allow to rebind keys/create macros on any keyboard independent of it's manufacturer. ColourShift, Gamesense, recordable macros and all other features are implemented purely in software and don't have much to do with specific keyboard models (beyond per-keyboard lighting). ApexCtl is only meant to access basic keyboard's hardware functionality - such as enabling keys that are disabled by default for some reason.
