### ISSUE TITLE
INSTALL_ROOT for make install not working (required for AUR)

### ISSUE THREAD

**Issue by phortx** [tuxmark5/ApexCtl#37]
I've wrote a PKGBUILD for ArchLinux in order to bring ApexCtl to the AUR: https://github.com/phortx/apexctl-git-aur

Unfortunately it seems like `make install` ignores `INSTALL_ROOT`, which is required to create the package file.

Can you fix that?

**Comment by kiwistrongis** [comment]
Is this good?: d804a19ea77acedb03cdc5c4016aca558613c96a

Also, thanks, I've been kinda meaning to do that for a while.

**Comment by phortx** [comment]
Yes, looks good as far as I can see :) Thank you.
