### ISSUE TITLE
install: cannot create regular file ‘/asdf/usr/local/bin/apexctl’?

### ISSUE THREAD

**Issue by Kai7os** [tuxmark5/ApexCtl#40]
Hi guys!
Thank you for creating this tool for us to use our keyboards on linux.

Im trying to run `make && sudo make install` on ubuntu 14.04 64bit and im getting the error in the title.
Whats going on? how do I fix this?

> 
> [ -f apexctl ]
> [ -f dist/build/apexctl/apexctl ]
> #make dirs
> mkdir -p /asdf/etc/udev/hwdb.d
> mkdir -p /asdf/etc/udev/rules.d
> #install binary
> install -m 755 apexctl /asdf/usr/local/bin/apexctl
> install: cannot create regular file ‘/asdf/usr/local/bin/apexctl’: No such file or directory
> make: *** [install] Error 1
>

**Comment by infoholic** [comment]
Edit makefile, in line 9 remove asdf.

**Comment by Kai7os** [comment]
So thats what I thought as well... but it doesnt create it either way. Have no idea what 'asdf' is.

**Comment by phortx** [comment]
The `asdf` looks like debug code IMHO. That's a bug.

@tuxmark5 can tell ;)

**Comment by Kai7os** [comment]
@tuxmark5 please obi-tux kenobi, you're my only hope.

**Comment by kiwistrongis** [comment]
Eeehhhhh I'm so sorry lol. Fixed as of bceb11b6dcbcf4da49cba4df5ed31229a5f44aff.
