### ISSUE TITLE
Problems with Ubuntu 16.04 and Apex 350

### ISSUE THREAD

**Issue by joscdk** [tuxmark5/ApexCtl#43]
I have just bought a SteelSeries Apex 350 keyboard, and installed your software on Ubuntu 16.04

I can fine use the apexctl command, but macro keys don't work, and even brightness and color commands don't change anything on the keyboard, any idea what the problem can be?

I installed the "Debian" packages from the installed.
Git cloned the ApexCtl to my Documents folder, and ran the global install.

I tried xev but no reaction to the macro keys.

Color command don't to anything

**Comment by tuxmark5** [comment]
Does it show any errors when running ApexCtl both without any arguments and when trying to change the colors?

**Comment by joscdk** [comment]
It dosn't give any response, as you can see on the image
![apexctl](https://cloud.githubusercontent.com/assets/2535140/17275596/a9fc4a86-570d-11e6-9da1-e01e2e988a0c.png)

**Comment by tuxmark5** [comment]
Looks like that with the Apex keyboard rebrand, they may have updated the
firmware as well. I'll try to update my own keyboard's firmware and
re-reverse-engineer the communication protocol.

**Comment by joscdk** [comment]
Thank you very much

**Comment by joscdk** [comment]
Hi @tuxmark5 

I added support for Coloring by adding the product ID from dmesg. I tried pushing a WIP feature branch, but wasn't allowed, i will try to work on the macro keys on my local, can you either allow me access to push feature branch, or i can just send you the code when i am done :-)

**Comment by joscdk** [comment]
Nvm, i needed to enable macrokeys :-)

If you allow me to push, i will push a feature branch, otherwise add 0x1206 in src/Main.hs:274

![apex350](https://cloud.githubusercontent.com/assets/2535140/17277373/900e09c8-5741-11e6-9e6e-33ec1055a6ec.png)

**Comment by mattboll** [comment]
Hi, I've got a brand new apex 350, this patch works great and is needed, so it should probably be merged, thanks all of you.

**Comment by oluthier** [comment]
Hi every body,
(sorry for my poor english)
I've just buy an apex 350 for my children today, and it seems that apexctl not run properly on my Ubuntu 16.04 too ...
@joscdk i hope you find the god way, but after a global install i am not be able to use color or anything else ...
Could someone explain to me how to make the good thing for ?
Thanks for the help

**Comment by markokacanski** [comment]
Hey,

I got the HP OMEN keyboard, which is re-branded Apex 350 - at least that's how it identifies itself in the /proc/bus/input/devices

It has a device id of 0x120a

I added 0x120a to the device array and I can change the color, and macro keys now trigger keypresses in xev

The keypresses are all wrong, they trigger volume up/down etc. but there is a https://github.com/tuxmark5/ApexCtl/issues/29 for that:
