### ISSUE TITLE
How to setup MX

### ISSUE THREAD

**Issue by ghost** [tuxmark5/ApexCtl#45]
Hey!

Thanx for your work, I did every step but I don´t know how to setup MX correctly.

Some doc?

thanx!

**Comment by tuxmark5** [comment]
You'll have to be more specific.

**Comment by ghost** [comment]
i don't know how to setup Xmodmap and/or 90-apex.hwdb  for use MX's keys (sorry for my english)
Thanks!
(And really thanx for your work)

**Comment by tuxmark5** [comment]
Just copy paste the given .Xmodmap file to your home directory. 
90-apex.hwdb should be copied to /etc/udev/hwdb.d/90-apex.hwdb

**Comment by ghost** [comment]
I did but I don't know how to assign text macros for MX's keys.

**Comment by tuxmark5** [comment]
You'll have to do macros with external tools. The ApexCtl utility only _enables_ the keys, so you can use them in other applications.

**Comment by ghost** [comment]
ok, thanx
